import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { v4 as uuidv4 } from 'uuid';
import { Sparkles, Copy, CheckCircle2, Wand2 } from 'lucide-react';
import type { Trip } from '@/types';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';

interface AIPromptGeneratorProps {
  trip: Trip;
}

export const AIPromptGenerator: React.FC<AIPromptGeneratorProps> = ({ trip }) => {
  const [preferences, setPreferences] = useState('');
  const [generatedPrompt, setGeneratedPrompt] = useState('');
  const [isCopied, setIsCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    
    // Simulate a slight delay for UX
    setTimeout(() => {
      const mockItinerary = `### 🌟 Your Magical Journey: ${trip.name}

Based on your vibe: "${preferences || 'A perfect balance of sightseeing, amazing food, and relaxation.'}"

#### 🌅 Day 1: Arrival & Local Vibes
- **Morning (10:00 AM)**: Arrive and settle in. Grab a quick local pastry and coffee near your accommodation to kickstart the adventure.
- **Afternoon (1:00 PM)**: Head out to explore the central district. Take it slow, soak in the architecture, and find a cozy hidden cafe for lunch.
- **Evening (6:30 PM)**: Enjoy a relaxed welcome dinner at a highly-rated local restaurant. Try to find a place that serves authentic regional dishes!

#### 🚶‍♂️ Day 2: Culture & Hidden Gems
- **Morning (9:30 AM)**: Visit the primary historical site or museum before the heavy crowds arrive. 
- **Afternoon (2:00 PM)**: Venture off the beaten path! Walk through the quieter, historic neighborhoods. Grab some famous local street food for a late lunch.
- **Evening (7:00 PM)**: Experience the nightlife! Whether it's a quiet speakeasy or a bustling night market, enjoy the vibrant evening atmosphere.

#### 🌄 Day 3: Scenic Views & Farewell
- **Morning (8:30 AM)**: Early start! Head to a famous viewpoint, park, or nature trail to catch the stunning morning light.
- **Afternoon (12:30 PM)**: Last-minute souvenir shopping in the boutique district and a hearty farewell lunch at a famous local spot.
- **Evening**: Pack up and head to the airport or train station for departure. Safe travels!

---
*✨ Magic generated by GlobeTrotter AI. Have a wonderful trip!*`;

      setGeneratedPrompt(mockItinerary);
      setIsCopied(false);
      setIsGenerating(false);
    }, 1500);
  };

  const handleCopy = () => {
    if (!generatedPrompt) return;
    navigator.clipboard.writeText(generatedPrompt);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [isApplied, setIsApplied] = useState(false);
  const [isApplying, setIsApplying] = useState(false);

  const handleApply = () => {
    setIsApplying(true);
    setTimeout(() => {
      queryClient.setQueryData<Trip>(['trip', trip.id], (old) => {
        if (!old) return old;
        
        const newActivities = [
          {
            id: uuidv4(),
            stopId: old.stops?.[0]?.id || uuidv4(),
            activityId: uuidv4(),
            dayNumber: 1,
            timeSlot: 'Morning',
            activity: {
              id: uuidv4(),
              name: '✨ Magic AI Exploration',
              description: 'An AI-curated morning exploring hidden gems and iconic sights.',
              duration: 3,
              cost: 0,
              category: 'Sightseeing',
              imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=800'
            }
          },
          {
            id: uuidv4(),
            stopId: old.stops?.[0]?.id || uuidv4(),
            activityId: uuidv4(),
            dayNumber: 1,
            timeSlot: 'Afternoon',
            activity: {
              id: uuidv4(),
              name: '✨ Magic Food Tasting',
              description: 'Taste the best authentic local cuisine recommended by AI.',
              duration: 2,
              cost: 45,
              category: 'Food',
              imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800'
            }
          }
        ];

        let newStops = old.stops || [];
        if (newStops.length > 0) {
          newStops = newStops.map((stop, index) => {
            if (index === 0) {
              return {
                ...stop,
                activities: [...(stop.activities || []), ...newActivities.map(a => ({ ...a, stopId: stop.id }))]
              };
            }
            return stop;
          });
        } else {
          newStops = [{
            id: uuidv4(),
            tripId: old.id,
            cityId: 'mock-city',
            startDate: old.startDate,
            endDate: old.endDate,
            orderIndex: 0,
            city: {
              id: 'mock-city',
              name: 'AI Recommended City',
              country: 'Wonderland',
              costIndex: 3,
              imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&q=80&w=800'
            },
            activities: newActivities
          }];
        }

        return { ...old, stops: newStops };
      });
      
      setIsApplying(false);
      setIsApplied(true);
      
      // Navigate to builder to see the magic
      navigate(`/trips/${trip.id}/builder`);
      
      setTimeout(() => setIsApplied(false), 3000);
    }, 800);
  };

  return (
    <Card className="bg-gradient-to-br from-background to-primary/5 border-primary/20 shadow-sm mb-8">
      <div className="p-6">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-6 h-6 text-primary" />
          <h2 className="text-xl font-bold text-textPrimary">Design Your Dream Journey</h2>
        </div>
        <p className="text-textSecondary mb-6 text-sm max-w-3xl">
          Let magic plan your trip! Tell us what you love to do, and we'll craft the perfect, personalized adventure tailored just for you and your destinations.
        </p>

        <div className="space-y-4">
          <div className="flex flex-col gap-1.5">
            <label className="text-sm font-medium text-textPrimary">
              What's your travel vibe?
            </label>
            <textarea
              className="flex w-full rounded-xl border border-border bg-background px-4 py-3 text-base placeholder:text-textSecondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 transition-colors min-h-[100px] resize-y"
              placeholder="e.g. I want a relaxed trip, focusing on cheap street food, hidden gems, and avoiding heavy crowds. I wake up late around 10 AM."
              value={preferences}
              onChange={(e) => setPreferences(e.target.value)}
            />
          </div>

          <Button 
            onClick={handleGenerate} 
            disabled={isGenerating || isApplying}
            className="w-full sm:w-auto gap-1.5"
          >
            {isGenerating ? (
              <>✨ Weaving the magic...</>
            ) : (
              <>✨ Cast the Magic Spell</>
            )}
          </Button>

          {generatedPrompt && (
            <div className="mt-6 animate-in fade-in slide-in-from-top-4 duration-500">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-3 gap-3">
                <label className="text-sm font-medium text-textPrimary">
                  Your Magic AI Itinerary
                </label>
                <div className="flex items-center gap-2">
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    onClick={handleCopy}
                    className={`h-9 px-3 text-sm ${isCopied ? 'text-green-600 hover:text-green-700 hover:bg-green-50' : 'text-textSecondary hover:text-primary'}`}
                  >
                    {isCopied ? (
                      <><CheckCircle2 className="w-4 h-4 mr-1.5" /> Copied</>
                    ) : (
                      <><Copy className="w-4 h-4 mr-1.5" /> Copy Text</>
                    )}
                  </Button>
                  <Button 
                    variant="primary" 
                    size="sm" 
                    onClick={handleApply}
                    disabled={isApplying || isApplied}
                    className={`h-9 px-4 text-sm font-semibold shadow-md ${isApplied ? 'bg-green-500 hover:bg-green-600' : ''}`}
                  >
                    {isApplying ? (
                      'Applying...'
                    ) : isApplied ? (
                      <><CheckCircle2 className="w-4 h-4 mr-1.5" /> Added to Itinerary</>
                    ) : (
                      <><Wand2 className="w-4 h-4 mr-1.5" /> Apply to Itinerary</>
                    )}
                  </Button>
                </div>
              </div>
              <div className="relative">
                <pre className="p-4 bg-gray-900 text-gray-100 rounded-xl overflow-x-auto text-sm font-mono whitespace-pre-wrap max-h-96 overflow-y-auto custom-scrollbar">
                  {generatedPrompt}
                </pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </Card>
  );
};
